//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExistingServices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExistingServices()
        {
            this.ServiceRequestsOk = new HashSet<ServiceRequestsOk>();
        }
    
        public int ServiceId { get; set; }
        public Nullable<int> IdOfferUser { get; set; }
        public string Description { get; set; }
        public Nullable<int> CostInPoint { get; set; }
        public Nullable<int> IdCategory { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestsOk> ServiceRequestsOk { get; set; }
    }
}
