//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequests
    {
        public int Id { get; set; }
        public Nullable<int> IdRequestingUser { get; set; }
        public string Description { get; set; }
        public Nullable<int> PointsCost { get; set; }
        public Nullable<System.DateTime> DateOfRequest { get; set; }
        public Nullable<int> IdCategory { get; set; }
        public Nullable<bool> RequestStatus { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Users Users { get; set; }
    }
}
