//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequestsOk
    {
        public int Id { get; set; }
        public Nullable<int> IdService { get; set; }
        public Nullable<int> IdOfferUser { get; set; }
        public Nullable<int> IdRequestingUser { get; set; }
        public Nullable<bool> CustomerRequestOk { get; set; }
        public Nullable<bool> OffersServiceOK { get; set; }
        public Nullable<System.DateTime> ExecutionDate { get; set; }
        public Nullable<int> ServiceScore { get; set; }
    
        public virtual ExistingServices ExistingServices { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
