//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.ExistingServices = new HashSet<ExistingServices>();
            this.ServiceRequests = new HashSet<ServiceRequests>();
            this.ServiceRequestsOk = new HashSet<ServiceRequestsOk>();
            this.ServiceRequestsOk1 = new HashSet<ServiceRequestsOk>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Tz { get; set; }
        public string PhoneNumber { get; set; }
        public string CityAdress { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> PointsNum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExistingServices> ExistingServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequests> ServiceRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestsOk> ServiceRequestsOk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestsOk> ServiceRequestsOk1 { get; set; }
    }
}
